(TeX-add-style-hook "paper"
 (lambda ()
    (TeX-run-style-hooks
     "indentfirst"
     ""
     "hyperref"
     "unicode"
     "pdftex"
     "babel"
     "english"
     "russian"
     "inputenc"
     "utf8"
     "fontenc"
     "T2A"
     "geometry"
     "bindingoffset=0cm"
     "bottom=2cm"
     "top=2cm"
     "right=2cm"
     "left=2cm"
     "latex2e"
     "art12"
     "article"
     "12pt"
     "a4paper")))

